REGRESSION (r278121): Fix build failure due to weak external symbol
Occurs when building coverage+release builds:

    ERROR: symbol _DDHighlightCreateWithRectsInVisibleRectWithStyleScaleAndDirection

The soft-linked symbol was originally added in r259276.

* Configurations/WebCore.unexp:
- Add _DDHighlightCreateWithRectsInVisibleRectWithStyleScaleAndDirection
  to the list of unexported symbols.
- Also sort symbols in the group alphabetically.

git-svn-id: http://svn.webkit.org/repository/webkit/trunk@278461 268f45cc-cd09-0410-ab3c-d52691b4dbfc