REGRESSION(r287412)[WinCairo] error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). https://bugs.webkit.org/show_bug.cgi?id=234658
Unreviewed build fix.

After r287412, WinCairo Debug can't compile due to the following error.

> C:\MSVS\VC\Tools\MSVC\14.28.29910\include\type_traits(1066):
>   error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)).
>   Before VS 2017 15.8, the member "type" would non-conformingly have an alignment of only alignof(max_align_t).
>   VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility
>   (*only* for uses of aligned_storage with extended alignments).
>   Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment,
>   or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conforming behavior.

* Source/cmake/OptionsMSVC.cmake: Added _ENABLE_EXTENDED_ALIGNED_STORAGE macro.

git-svn-id: http://svn.webkit.org/repository/webkit/trunk@287422 268f45cc-cd09-0410-ab3c-d52691b4dbfc